# Hold defs of writing functions for datacard
import math
import os, sys, re
from numbers import Real
from commonTools import *
from commonObjects import *

def writePreamble(f,options):
  f.write("CMS HZa Datacard - %s - %s\n"%(options.years,sqrts__)) 
  f.write("Auto-generated by flashggFinalFits/Datacard/makeDatacard.py\n")
  f.write("Run with: combine\n")
  f.write("---------------------------------------------\n")
  f.write("imax *\n")
  f.write("jmax *\n")
  f.write("kmax *\n")
  f.write("---------------------------------------------\n")
  return True

def writeProcesses(f,d,options):
  f.write("\n")
  # If opt.prune then remove all rows from dataFrame with prune=1
  if options.prune: d = d[d['prune']==0]
  # d = Pandas DataFrame
  # Shapes
  # Loop over categories in dataframe
  for cat in d.cat.unique():
    # Loop over rows for respective category
    for ir,r in d[d['cat']==cat].iterrows():
      # Write to datacard
      f.write("shapes      %-26s %-7s %s %s\n"%(r['proc'],r['cat'],r['modelWSFile'],r['model']))

  # Bin, observation and rate lines
  lbreak = '-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
  lbin_cat = '%-15s'%"bin"
  lobs_cat = '%-15s'%"observation"
  lbin_procXcat = '%-15s'%"bin"
  lproc = '%-15s'%"process"
  lprocid = '%-15s'%"process"
  lrate = '%-15s'%"rate"        
  # Loop over categories
  for cat in d.cat.unique():
    lbin_cat += "%-20s "%cat
    lobs_cat += "%-20s "%"-1"
    sigID = 0
    # Loop over rows for respective category
    for ir,r in d[d['cat']==cat].iterrows():
      if r['proc'] == "data_obs": continue
      lbin_procXcat += "%-20s "%cat
      lproc += "%-20s "%r['proc']
      if r['proc'] == "bkg_mass": lprocid += "%-20s "%"1"
      else:
        lprocid += "%-20s "%sigID
        sigID -= 1
      if r['rate'] == 1.0: lrate += "%-20.1f "%r['rate']
      else: lrate += "%-20.1f "%r['rate']
  #Remove final space from lines and add to file
  f.write("\n")
  for l in [lbreak,lbin_cat,lobs_cat,lbreak,lbin_procXcat,lproc,lprocid,lrate,lbreak]: 
    l = l[:-1]
    f.write("%s\n"%l)
    
  f.write("\n")
  return True


def writeSystematic(f,d,s,options,stxsMergeScheme=None,scaleCorrScheme=None):

  # For signal shape systematics add simple line
  if s['type'] == 'signal_shape':
    stitle = "%s_%s"%(outputWSNuisanceTitle__,s['title'])
    if s['mode'] != 'other':
      if outputNuisanceExtMap[s['mode']] != '':
        stitle += "_%s"%outputNuisanceExtMap[s['mode']]
    # If not correlated: separate nuisance per year
    if s['mode'] in ['scales','smears']:
      for year in options.years.split(","):
        stitle_y = "%s_%s"%(stitle,year) 
        lsyst = "%-70s  param    %-6s %-6s"%(stitle_y,s['mean'],s['sigma'])
        f.write("%s\n"%lsyst)
    else:
      lsyst = "%-70s  param    %-6s %-6s"%(stitle,s['mean'],s['sigma'])
      f.write("%s\n"%lsyst)
    return True
 
  # Else: for yield variation uncertainties...
  # Remove all rows from dataFrame with prune=1 (includes NoTag)
  if options.prune:
    mask = (d['prune']==0)
    d = d[mask]

  # If theory: loop over tiers else run over once
  tiers = []
  if 'tiers' in s: tiers = s['tiers']
  if(not options.doSTXSMerging)&('mnorm' in tiers): tiers.remove("mnorm")
  if len(tiers)==0: tiers = ['']
  for tier in tiers:
    if tier != '': tierStr = "_%s"%tier
    else: tierStr = ''
    
    # If calculating merged bin: loop over mergings else run over once
    mns = []
    if tier == 'mnorm':
      if options.doSTXSMerging:
        for mergeName in stxsMergeScheme: mns.append(mergeName)
    if len(mns) == 0: mns.append('')
    for mn in mns:
      if mn != '': mergeStr = "_%s"%mn
      else: mergeStr = ''
    
      # Construct syst line/lines if separate by year
      if(s['correlateAcrossYears'] == 1)|(s['correlateAcrossYears'] == -1):
        stitle = "%s%s%s"%(s['title'],mergeStr,tierStr)
        lsyst = '%-50s  %-10s    '%(stitle,s['prior'])
        # Loop over categories and then iterate over rows in category
        for cat in d.cat.unique():
          for ir,r in d[d['cat']==cat].iterrows():
            if r['proc'] == "data_obs": continue
            # Extract value and add to line (with checks)
            sval = r["%s%s%s"%(s['name'],mergeStr,tierStr)]
            lsyst = addSyst(lsyst,sval,stitle,r['proc'],cat)
        # Remove final space from line and add to file
        f.write("%s\n"%lsyst[:-1])
        # For uncorrelated scale weights: not for merged bins
        if options.doSTXSScaleCorrelationScheme:
          if(tier!='mnorm')&("scaleWeight" in s['name']):
            for ps,psProcs in scaleCorrScheme.items():
              psStr = "_%s"%ps
              stitle = "%s%s%s"%(s['title'],psStr,tierStr)
              lsyst = '%-50s  %-10s    '%(stitle,s['prior'])
              # Loop over categories and then iterate over rows in category
              for cat in d.cat.unique():
                for ir,r in d[d['cat']==cat].iterrows():
                  if r['proc'] == "data_obs": continue
                  # Remove year+hgg tags from proc
                  p = re.sub("_2016_hgg","",r['proc'])
                  p = re.sub("_2017_hgg","",p)
                  p = re.sub("_2018_hgg","",p)
                  p = re.sub("_2022preEE_hgg","",p)
                  p = re.sub("_2022postEE_hgg","",p)
                  # Add value if in proc in phase space else -
                  if p in psProcs: sval = r["%s%s"%(s['name'],tierStr)]
                  else: sval = '-'
                  lsyst = addSyst(lsyst,sval,stitle,r['proc'],cat)
              # Remove final space from line and add to file
              f.write("%s\n"%lsyst[:-1])
      else:
        for year in options.years.split(","):
          stitle = "%s%s%s_%s"%(s['title'],mergeStr,tierStr,year)
          sname = "%s%s%s_%s"%(s['name'],mergeStr,tierStr,year)
          lsyst = '%-50s  %-10s    '%(stitle,s['prior'])
          # Loop over categories and then iterate over rows in category
          for cat in d.cat.unique():
            for ir,r in d[d['cat']==cat].iterrows():
              if r['proc'] == "data_obs": continue
              # Extract value and add to line (with checks)
              sval = r[sname]
              lsyst = addSyst(lsyst,sval,stitle,r['proc'],cat)
          # Remove final space from line and add to file
          f.write("%s\n"%lsyst[:-1])
  return True


def addSyst(l,v,s,p,c):
  #l-systematic line, v-value, s-systematic title, p-proc, c-cat
  def _append_dash(line):
    line += "%-15s " % "-"
    return line

  if isinstance(v, str): 
    l += "%-15s "%v
    return l
  if v is None:
    return _append_dash(l)
  if hasattr(v, "tolist") and not isinstance(v, (str, bytes)):
    v = v.tolist()
  if isinstance(v, tuple):
    v = list(v)
  if isinstance(v, Real):
    vf = float(v)
    if not math.isfinite(vf):
      return _append_dash(l)
    v = [vf]
  elif isinstance(v, list):
    pass
  else:
    print(" --> [ERROR] systematic %s: unsupported value type %s for (%s,%s), value=%r. Leaving..."%(s,type(v).__name__,p,c,v))
    sys.exit(1)

  if isinstance(v, list): 
    if len(v) == 0:
      return _append_dash(l)
    try:
      vals = [float(x) for x in v]
    except Exception:
      print(" --> [ERROR] systematic %s: list contains non-numeric values for (%s,%s), value=%r. Leaving..."%(s,p,c,v))
      sys.exit(1)
    if any(not math.isfinite(x) for x in vals):
      return _append_dash(l)
    v = vals
    # Symmetric:
    if len(v) == 1: 
      # Check 1: variation is non-negligible. If not then skip
      if abs(v[0]-1)<0.0005: 
        print(" --> [INFO] 忽略 systematics %s (proc=%s, cat=%s) 值=%.6f |Δ|=%.6g < 0.0005"%(s,p,c,v[0],abs(v[0]-1)))
        l += "%-15s "%"-"
      # Check 2: variation is not negative. Print message and add - to datacard (cleaned later)
      elif v[0] < 0.: 
        print(" --> [WARNING] systematic %s: negative variation for (%s,%s)"%(s,p,c))
        #vstr = "%s"%v[0]
        vstr = "-"
        l += "%-15s "%vstr
      else:
        l += "%-15.3f "%v[0]
    # Anti-symmetirc
    if len(v) == 2:
      # Check 1: variation is non-negligible. If not then skip
      if(abs(v[0]-1)<0.0005)&(abs(v[1]-1)<0.0005): 
        print(" --> [INFO] 忽略 systematics %s (proc=%s, cat=%s) 上下變動=%.6f/%.6f |Δ_up|=%.6g |Δ_down|=%.6g 皆 < 0.0005"%(s,p,c,v[0],v[1],abs(v[0]-1),abs(v[1]-1)))
        l += "%-15s "%"-"
      # Check 2: neither variation is negative. Print message and add - to datacard (cleaned later)
      elif(v[0]<0.)|(v[1]<0.):
        print(" --> [WARNING] systematic %s: negative variation for (%s,%s)"%(s,p,c))
        #vstr = "%.3f/%.3f"%(v[0],v[1])
        vstr = "-"
        l += "%-15s "%vstr
      # Check 3: effect is approximately symmetric: then just add single up variation
      elif( abs((v[0]*v[1])-1)<0.0005 ): l += "%-15.3f "%v[1]
      else: 
        vstr = "%.3f/%.3f"%(v[0],v[1])
        l += "%-15s "%vstr
    return l

def writeMCStatUncertainty(f,d,options):
 
  # Remove all rows from dataFrame with prune=1 (includes NoTag)
  if options.prune:
    mask = (d['prune']==0)
    d = d[mask]

  # Separate nuisance for each cat * years: ~Barlow-Beeston-Lite approach
  for scat in d.cat.unique():
    for year in options.years.split(","):
      # Extract sval
      mask = (d['year']==year)&(d['cat']==scat)&(d['type']=='sig')
      sumw = d[mask]['nominal_yield'].sum()
      sumw2 = d[mask]['sumw2'].sum()
      scval = [1+(math.sqrt(sumw2)/sumw)]
      d[d['type']=='sig']
      stitle = "MCStat_%s_%s"%(year,scat)
      sprior = "lnN"
      lsyst = '%-50s  %-10s    '%(stitle,sprior)
      # Loop over categories and then iterate over rows in category
      for cat in d.cat.unique():
        for ir,r in d[d['cat']==cat].iterrows():
          if r['proc'] == "data_obs": continue
          elif r['type'] == "sig": 
            sval = scval if cat == scat else '-'
          else:
            sval = '-'
          # Extract value and add to line (with checks)
          lsyst = addSyst(lsyst,sval,stitle,r['proc'],cat)
      # Remove final space from line and add to file
      f.write("%s\n"%lsyst[:-1])
  
  return True


def writePdfIndex(f,d,options):
  f.write("\n")
  for cat in d[~d['cat'].str.contains("NOTAG")].cat.unique(): 
    indexStr = "pdfindex_%s_13p6TeV"%cat
    f.write("%-15s  discrete\n"%indexStr)
  return True

def writeBreak(f):
  lbreak = '-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
  f.write("%s\n"%lbreak)

def writeInterpolateYields(f,d,s,options,stxsMergeScheme=None,scaleCorrScheme=None):
  import json

  # Anchor points (真正有產出 workspace/yields 的點)
  ma_list = [1,2,3,4,5,6,7,8,9,10,15,20,25,30]
  interploate_ma_list = [11,12,13,14,16,17,18,19,21,22,23,24,26,27,28,29]

  def _nearest_anchor_mass(mass, anchors):
    m = int(round(float(mass)))
    return min(anchors, key=lambda a: abs(a - m))

  def resolve_mass_for_io(mass_alp, anchors, interpolate_list):
    m = int(round(float(mass_alp)))
    if m in interpolate_list:
      return _nearest_anchor_mass(m, anchors)
    return m

  def _load_eff_json(ch):
    # ch: 'ele' or 'mu'
    if ch == "ele":
      path = "/afs/cern.ch/work/p/pelai/HZa/HiggsZaAna/Plot/output/sigEfficiencyVmA_ele_byYear_5years_quadratic_interp_ma_points.json"
    elif ch == "mu":
      path = "/afs/cern.ch/work/p/pelai/HZa/HiggsZaAna/Plot/output/sigEfficiencyVmA_muon_byYear_5years_quadratic_interp_ma_points.json"
    else:
      raise ValueError("Unknown channel: %s" % ch)
    with open(path, "r") as jf:
      return json.load(jf)

  def _get_eff(payload, year, mass):
    # json keys for mass are strings: "1","2",...
    mkey = str(int(round(float(mass))))
    try:
      return float(payload["values"][year][mkey])
    except Exception as e:
      raise KeyError("Cannot find eff for year=%s mass=%s in json (%s)" % (year, mkey, str(e)))

  # 只在需要插值的點寫 rateParam（call site 已經用 if opt.mass_ALP in interploate_ma_list 保護）
  mass_target = int(round(float(options.mass_ALP)))
  mass_for_io = resolve_mass_for_io(mass_target, ma_list, interploate_ma_list)

  years = [y.strip() for y in options.years.split(",") if y.strip()]
  # datacard relevant cats: 跟 pdfindex 一樣排除 NOTAG；rateParam 對每個 cat 寫一行
  cats = [c for c in d.cat.unique() if ("NOTAG" not in c)]

  # 讀入兩個 channel json
  eff_json = {
    "ele": _load_eff_json("ele"),
    "mu": _load_eff_json("mu"),
  }

  # 確保有空行分隔（可選）
  f.write("\n")

  # rateParam lines: per (year,channel,cat)
  for year in years:
    for ch in ["ele", "mu"]:
      eff_t = _get_eff(eff_json[ch], year, mass_target)
      eff_a = _get_eff(eff_json[ch], year, mass_for_io)
      ratio = (eff_t / eff_a) if eff_a != 0.0 else 1.0

      nuis = "interpolate_yield_%s_%s" % (year, ch)
      proc = "ggH_%s_%s" % (year, ch)

      for cat in cats:
        f.write("%-37s rateParam   %-6s %-22s %.16g\n" % (nuis, cat, proc, ratio))

  f.write("\n")

  # freeze lines: 每個 (year,channel) 一行
  for year in years:
    for ch in ["ele", "mu"]:
      nuis = "interpolate_yield_%s_%s" % (year, ch)
      f.write("nuisance edit freeze %s\n" % nuis)

  return True
